---
name: "Matrix Tests"

on:
  pull_request:
    paths-ignore:
      - '.github/workflows/test2.yml'
#  push:

concurrency:
  # yamllint disable rule:line-length
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ github.event.pull_request.number || github.run_id }}
  # yamllint enable rule:line-length
  cancel-in-progress: true

jobs:

  prepare:
    name: Prepare
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Prepare stuff!"

  build:
    needs: [prepare]
    strategy:
      fail-fast: false
      matrix:
        target: [a, b, c, d]
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Buld stuff ${{ matrix.target }}"
      - run: sleep 5
      - run: |
          if [ "${{ matrix.target }}" == "9" ] ; then exit 1; fi;
      - run: echo "Buld done!"

  # Workarround so that there is a single job for the status check
  build-complete:
    name: All Targets Build
    runs-on: ubuntu-22.04
    needs: [build]
    if: ${{ !cancelled() }}
    steps:
#      - run: |
#          echo "Needs context: ${{ toJson(needs) }}"
      - name: Error out because there is a failure
        if: ${{ needs.build.result != 'success' }}
        run: |
          echo "Build Matrix Result: ${{ needs.build.result }}"
          exit 1
      - name: All firmware builds succeded
        run: echo "All firmware builds succeded!"
