---
name: "Check Tests"

on:
  pull_request:
#  push:

concurrency:
  # yamllint disable rule:line-length
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ github.event.pull_request.number || github.run_id }}
  # yamllint enable rule:line-length
  cancel-in-progress: true

jobs:

  prepare:
    name: Prepare
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Prepare stuff!"

  # Workarround so that there is a single job for the status check
  build-complete:
    name: Check
    runs-on: ubuntu-22.04
    needs: [prepare]
    steps:
      - name: Error out on purpose
        run: exit 1
      - name: All checks succeded
        run: echo "All checks succeded!"
